semappsBundle\Entity\Organization:
    type: entity
    table: null
    repositoryClass: semappsBundle\Repository\OrganizationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        sfOrganisation:
            type: text
            nullable: true
        graphURI:
            type: text
            length: 255
            nullable: true
        fkResponsable:
            type: integer
            nullable: true
        organisationPicture:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
