parameters:

    placeConf:
      type: 'http://virtual-assembly.org/pair#Place'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Place'
      nameType: 'place'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
           value: 'hasInterest'
           access: 'anonymous'
        http://virtual-assembly.org/pair#hasType:
          value: 'hasType'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#hasPart:
          value: 'hasPart'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#partOf:
          value: 'partOf'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#deliveredBy:
          value: 'deliveredBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#operatedBy:
          value: 'operatedBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#adress:
          value: 'address'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adressLine2:
          value: 'complementAddress'
          access: 'anonymous'
        http://virtual-assembly.org/pair#e-mail:
          value: 'email'
          access: 'member'
        http://virtual-assembly.org/pair#phone:
          value: 'phone'
          access: 'member'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hosts:
          value: 'hosts'
          access: 'anonymous'
          type: 'uri'
      reverse:
        http://virtual-assembly.org/pair#hasType: 'http://virtual-assembly.org/pair#typeOf'
        http://virtual-assembly.org/pair#hosts: 'http://virtual-assembly.org/pair#isHostedIn'

      label:
        - http://virtual-assembly.org/pair#preferedLabel