GrandsVoisinsBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: GrandsVoisinsBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sfLink:
            type: text
            nullable: true
        sfUser:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
