parameters:

    documentConf:
      type: 'http://virtual-assembly.org/pair#Document'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Document'
      nameType: 'document'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#represents:
#          value: 'represents'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#documents:
          value: 'documents'
          access: 'anonymous'
        http://virtual-assembly.org/pair#references:
          value: 'references'
          access: 'anonymous'
        http://virtual-assembly.org/pair#referencesBy:
          value: 'referencesBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasType:
          value: 'hasType'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_document_author:
          value: 'internal_document_author'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_document_contributor:
          value: 'internal_document_contributor'
          access: 'anonymous'
        http://virtual-assembly.org/pair#external_document_author: #person + orga
          value: 'external_document_author'
          access: 'anonymous'
        http://virtual-assembly.org/pair#external_document_contributor: #person + orga
          value: 'external_document_contributor'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_document_publisher: #person + orga
           value: 'internal_document_publisher'
           access: 'anonymous'
        http://virtual-assembly.org/pair#external_document_publisher: # person + orga
           value: 'external_document_publisher'
           access: 'anonymous'
        http://virtual-assembly.org/pair#format:
           value: 'format'
           access: 'anonymous'
        http://virtual-assembly.org/pair#language:
           value: 'language'
           access: 'anonymous'
        http://virtual-assembly.org/pair#licence:
           value: 'licence'
           access: 'anonymous'
        http://virtual-assembly.org/pair#publicationDate:
           value: 'publicationDate'
           access: 'anonymous'
#        http://virtual-assembly.org/pair#source:
#           value: 'source'
#           access: 'anonymous'
        http://virtual-assembly.org/pair#version:
           value: 'version'
           access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
           value: 'hasInterest'
           access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
           value: 'hasSubject'
           access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#references: 'http://virtual-assembly.org/pair#referencesBy'
        http://virtual-assembly.org/pair#hasType: 'http://virtual-assembly.org/pair#typeOf'
        http://virtual-assembly.org/pair#documents: 'http://virtual-assembly.org/pair#documentedBy'
        http://virtual-assembly.org/pair#internal_document_author: 'http://virtual-assembly.org/pair#internal_author'
        http://virtual-assembly.org/pair#internal_document_contributor: 'http://virtual-assembly.org/pair#internal_contributor'
        http://virtual-assembly.org/pair#internal_document_publisher: 'http://virtual-assembly.org/pair#internal_publisher'
      label:
        - http://virtual-assembly.org/pair#preferedLabel